org: rgzimring
app: heatstrike
service: heatstrike

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-2
  httpApi:
    cors: true
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 7
  versionFunctions: false
  environment:
    OPTIONS_TABLE_NAME:
      Ref: OptionsTable
    TICKERS_BUCKET_NAME:
      Ref: TickersBucket
    TRADIER_KEY: ${ssm:tradier-api-key}
    BUG_REPORT_EMAIL: ${ssm:bug-report-email}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [OptionsTable, Arn]
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: '*'
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - Fn::Join:
                - ''
                - - Fn::GetAtt: [TickersBucket, Arn]
                  - '/*'

functions:
  OptionsAPI:
    handler: lambdas/api.handler
    name: ${self:provider.stage}-${self:service}-options-api
    memorySize: 256
    timeout: 29
    events:
      - httpApi:
          path: /data/{ticker}
          method: GET
      - httpApi:
          path: /openapi.json
          method: GET
      - httpApi:
          path: /bug-report
          method: POST
      - httpApi:
          path: /tickers
          method: GET

  RefreshTickers:
    handler: lambdas/refreshTickers.handler
    name: ${self:provider.stage}-${self:service}-refresh-tickers
    memorySize: 256
    timeout: 30
    events:
      - schedule: rate(1 day)

resources:
  Resources:
    OptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ticker
            AttributeType: S
        KeySchema:
          - AttributeName: ticker
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.stage}-${self:service}-options-table

    TickersBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-${self:service}-tickers
